# Generated by Django 5.1 on 2024-10-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_csvfile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('plot_data', models.JSONField()),
                ('image', models.ImageField(upload_to='plots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
