# Generated by Django 5.1 on 2024-10-24 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_savedplot_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedplot',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='savedplot',
            name='image',
        ),
        migrations.AddField(
            model_name='savedplot',
            name='plot_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savedplot',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='savedplot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
