# Generated by Django 5.1 on 2024-10-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_savedplot_created_at_remove_savedplot_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedplot',
            name='image',
            field=models.ImageField(default=1, upload_to='plots/'),
            preserve_default=False,
        ),
    ]
