# Generated by Django 5.1 on 2024-10-24 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_savedplot_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedplot',
            name='image',
        ),
    ]
