# Generated by Django 5.1 on 2024-10-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_savedplot_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedplot',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
